"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  ArrowRight,
  BarChart3,
  Bell,
  CalendarDays,
  Check,
  CircleDot,
  ClipboardCopy,
  Clock3,
  Compass,
  IndianRupee,
  LayoutDashboard,
  LoaderCircle,
  MapPin,
  Menu,
  MessageSquareText,
  Plus,
  RefreshCw,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  Swords,
  Trash2,
  Trophy,
  Users,
  X,
} from "lucide-react";
import type { ChatGPTUser } from "./chatgpt-auth";
import ThemeToggle from "./theme-toggle";

type View = "Overview" | "Tournaments" | "Teams" | "Fixtures" | "Matchday" | "Standings" | "Inbox";
type Tournament = { id: string; name: string; organizedBy: string; city: string; venueName: string; addressLine1: string; locality: string; state: string; postalCode: string; latitude: string; longitude: string; startDate: string; durationDays: number; status: string; contactName: string; contactPhone: string; createdAt: string };
type Division = { id: string; tournamentId: string; name: string; format: string; maxSquadSize: number; maxTeams: number; feePaise: number; feeBasis: string; requirePlayers: boolean; requireDocuments: boolean; winPoints: number; drawPoints: number; lossPoints: number };
type Entry = { id: string; divisionId: string; teamId: string; teamName: string; clubName: string; city: string; contactName: string; contactPhone: string; status: string; paymentStatus: string; amountPaise: number; registeredAt: string };
type Fixture = { id: string; divisionId: string; roundNumber: number; roundName: string; homeEntryId: string; awayEntryId: string; kickoffAt: string; pitch: number; status: string; homeScore: number; awayScore: number };
type MatchEvent = { id: string; fixtureId: string; entryId: string; type: string; playerName: string; matchMinute: number; createdAt: string };
type Announcement = { id: string; tournamentId: string; body: string; audience: string; createdAt: string };
type AppData = { tournaments: Tournament[]; divisions: Division[]; entries: Entry[]; fixtures: Fixture[]; events: MatchEvent[]; announcements: Announcement[] };

const emptyData: AppData = { tournaments: [], divisions: [], entries: [], fixtures: [], events: [], announcements: [] };
const nav: Array<{ label: View; icon: typeof Trophy }> = [
  { label: "Overview", icon: LayoutDashboard }, { label: "Tournaments", icon: Trophy }, { label: "Teams", icon: ShieldCheck },
  { label: "Fixtures", icon: CalendarDays }, { label: "Matchday", icon: Swords }, { label: "Standings", icon: BarChart3 }, { label: "Inbox", icon: MessageSquareText },
];
const ageOptions = ["U-10", "U-12", "U-14", "U-16", "U-18", "Open"];

const money = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);
const dateLabel = (date: string) => new Date(`${date}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
const timeLabel = (date: string) => new Date(date).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Kolkata" });

function Logo() {
  return <div className="brand"><span className="brand-mark"><CircleDot size={21} strokeWidth={2.4} /></span><span>my<span>football</span></span></div>;
}

function Modal({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: React.ReactNode }) {
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><div className="modal-top"><div><span className="eyebrow">MyFootball operations</span><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-button" onClick={onClose}><X size={19} /></button></div>{children}</div></div>;
}

function CreateTournament({ onClose, onSaved }: { onClose: () => void; onSaved: (payload: Record<string, unknown>) => Promise<void> }) {
  const [ages, setAges] = useState(["U-14"]);
  const [busy, setBusy] = useState(false);
  const [coords, setCoords] = useState({ latitude: "", longitude: "" });
  const usePosition = () => navigator.geolocation?.getCurrentPosition(position => setCoords({ latitude: position.coords.latitude.toFixed(6), longitude: position.coords.longitude.toFixed(6) }));
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true);
    const form = new FormData(event.currentTarget);
    await onSaved({ action: "createTournament", name: form.get("name"), organizedBy: form.get("organizedBy"), city: form.get("city"), venueName: form.get("venueName"), addressLine1: form.get("addressLine1"), locality: form.get("locality"), state: form.get("state"), postalCode: form.get("postalCode"), latitude: form.get("latitude"), longitude: form.get("longitude"), startDate: form.get("startDate"), durationDays: form.get("durationDays"), contactName: form.get("contactName"), contactPhone: form.get("contactPhone"), format: form.get("format"), maxTeams: form.get("maxTeams"), maxSquadSize: form.get("maxSquadSize"), feeRupees: form.get("feeRupees"), ageGroups: ages, requirePlayers: form.get("requirePlayers") === "on", requireDocuments: form.get("requireDocuments") === "on" });
    setBusy(false);
  };
  return <Modal title="Create a tournament" subtitle="Every field below is saved to your organizer account." onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="form-grid">
    <label className="field field-wide"><span>Tournament name</span><input name="name" placeholder="e.g. Kerala Youth Champions Cup" required autoFocus /></label>
    <label className="field"><span>Organized by</span><input name="organizedBy" placeholder="Academy or organization" required /></label>
    <label className="field"><span>Venue / ground name</span><input name="venueName" placeholder="Cooperage Football Ground" required /></label>
    <label className="field field-wide"><span>Street address</span><input name="addressLine1" placeholder="Maharshi Karve Road, Nariman Point" required /></label>
    <label className="field"><span>Locality / area</span><input name="locality" placeholder="Colaba" required /></label>
    <label className="field"><span>City</span><input name="city" placeholder="Mumbai" required /></label>
    <label className="field"><span>State</span><input name="state" placeholder="Maharashtra" required /></label>
    <label className="field"><span>PIN code</span><input name="postalCode" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} placeholder="400021" required /></label>
    <label className="field"><span>Latitude</span><input name="latitude" value={coords.latitude} onChange={event=>setCoords({...coords,latitude:event.target.value})} placeholder="18.924100" required /></label>
    <label className="field"><span>Longitude</span><input name="longitude" value={coords.longitude} onChange={event=>setCoords({...coords,longitude:event.target.value})} placeholder="72.829600" required /></label>
    <button className="location-helper field-wide" type="button" onClick={usePosition}><MapPin size={15}/> Use my current coordinates</button>
    <label className="field"><span>Start date</span><input name="startDate" type="date" required /></label>
    <label className="field"><span>Duration</span><select name="durationDays" defaultValue="2"><option value="1">1 day</option><option value="2">2 days</option><option value="3">3 days</option><option value="14">2 weeks</option><option value="28">4 weekends</option></select></label>
    <label className="field"><span>Contact name</span><input name="contactName" required /></label>
    <label className="field"><span>Contact phone</span><input name="contactPhone" type="tel" placeholder="+91..." required /></label>
    <label className="field"><span>Format</span><select name="format"><option value="group_knockout">Groups + Knockout</option><option value="round_robin">Round robin</option><option value="knockout">Knockout</option></select></label>
    <label className="field"><span>Maximum teams per division</span><select name="maxTeams" defaultValue="16"><option>8</option><option>12</option><option>16</option><option>24</option><option>32</option></select></label>
    <label className="field"><span>Maximum squad size</span><input name="maxSquadSize" type="number" min="5" max="50" defaultValue="18" /></label>
    <label className="field"><span>Fee per team (₹)</span><input name="feeRupees" type="number" min="0" defaultValue="0" /></label>
    <div className="field field-wide"><span>Divisions</span><div className="chip-picker">{ageOptions.map(age => <button type="button" className={ages.includes(age) ? "pick selected" : "pick"} key={age} onClick={() => setAges(current => current.includes(age) ? current.filter(item => item !== age) : [...current, age])}>{ages.includes(age) && <Check size={13} />}{age}</button>)}</div></div>
    <label className="toggle-row field-wide"><div><strong>Collect player lists</strong><small>Enable squad registration for this tournament</small></div><input name="requirePlayers" type="checkbox" /></label>
    <label className="toggle-row field-wide"><div><strong>Require age documents</strong><small>Use only when age verification is necessary</small></div><input name="requireDocuments" type="checkbox" /></label>
  </div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || !ages.length}>{busy ? <LoaderCircle className="spin" size={17} /> : <Plus size={17} />} Create tournament</button></div></form></Modal>;
}

function AddTeam({ divisions, onClose, onSaved }: { divisions: Division[]; onClose: () => void; onSaved: (payload: Record<string, unknown>) => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); await onSaved({ action: "addTeam", divisionId: form.get("divisionId"), clubName: form.get("clubName"), teamName: form.get("teamName"), organizationType: form.get("organizationType"), city: form.get("city"), contactName: form.get("contactName"), contactPhone: form.get("contactPhone"), paymentStatus: form.get("paymentStatus"), approved: form.get("approved") === "on" }); setBusy(false); };
  return <Modal title="Add a team" subtitle="Manual entries use the same database as public registrations." onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="form-grid">
    <label className="field field-wide"><span>Division</span><select name="divisionId">{divisions.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>
    <label className="field"><span>Club / academy</span><input name="clubName" required /></label><label className="field"><span>Team name</span><input name="teamName" required /></label>
    <label className="field"><span>Organization type</span><select name="organizationType"><option value="club">Club</option><option value="academy">Academy</option><option value="school">School</option><option value="institution">Institution</option></select></label><label className="field"><span>City</span><input name="city" /></label>
    <label className="field"><span>Contact person</span><input name="contactName" required /></label><label className="field"><span>Mobile number</span><input name="contactPhone" type="tel" required /></label>
    <label className="field"><span>Payment</span><select name="paymentStatus"><option value="unpaid">Unpaid</option><option value="paid">Paid</option><option value="waived">Waived</option></select></label><label className="toggle-row"><div><strong>Approve immediately</strong><small>Add to fixture pool</small></div><input name="approved" type="checkbox" defaultChecked /></label>
  </div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <Plus size={17} />} Save team</button></div></form></Modal>;
}

function SetLocation({ tournament, onClose, onSaved }: { tournament: Tournament; onClose: () => void; onSaved: (payload: Record<string, unknown>) => Promise<void> }) {
  const [coords,setCoords]=useState({latitude:tournament.latitude||"",longitude:tournament.longitude||""});
  const [busy,setBusy]=useState(false);
  const usePosition=()=>navigator.geolocation?.getCurrentPosition(position=>setCoords({latitude:position.coords.latitude.toFixed(6),longitude:position.coords.longitude.toFixed(6)}));
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);await onSaved({action:"updateLocation",tournamentId:tournament.id,venueName:form.get("venueName"),addressLine1:form.get("addressLine1"),locality:form.get("locality"),city:form.get("city"),state:form.get("state"),postalCode:form.get("postalCode"),latitude:form.get("latitude"),longitude:form.get("longitude")});setBusy(false);};
  return <Modal title="Set exact tournament location" subtitle="Fans will search this area and use the coordinates for map directions." onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="form-grid"><label className="field field-wide"><span>Venue / ground</span><input name="venueName" defaultValue={tournament.venueName} required/></label><label className="field field-wide"><span>Street address</span><input name="addressLine1" defaultValue={tournament.addressLine1} required/></label><label className="field"><span>Locality / area</span><input name="locality" defaultValue={tournament.locality} required/></label><label className="field"><span>City</span><input name="city" defaultValue={tournament.city} required/></label><label className="field"><span>State</span><input name="state" defaultValue={tournament.state} required/></label><label className="field"><span>PIN code</span><input name="postalCode" defaultValue={tournament.postalCode} pattern="[0-9]{6}" maxLength={6} required/></label><label className="field"><span>Latitude</span><input name="latitude" value={coords.latitude} onChange={event=>setCoords({...coords,latitude:event.target.value})} required/></label><label className="field"><span>Longitude</span><input name="longitude" value={coords.longitude} onChange={event=>setCoords({...coords,longitude:event.target.value})} required/></label><button className="location-helper field-wide" type="button" onClick={usePosition}><MapPin size={15}/> Use my current coordinates</button></div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<MapPin size={17}/>} Save location</button></div></form></Modal>;
}

function GenerateFixtures({ divisions, onClose, onSaved }: { divisions: Division[]; onClose: () => void; onSaved: (payload: Record<string, unknown>) => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); await onSaved({ action: "generateFixtures", divisionId: form.get("divisionId"), mode: form.get("mode"), startDate: form.get("startDate"), startTime: form.get("startTime"), pitches: form.get("pitches"), slotMinutes: form.get("slotMinutes") }); setBusy(false); };
  return <Modal title="Generate fixtures" subtitle="Approved teams are scheduled with pitch and time constraints." onClose={onClose}><form onSubmit={submit}><div className="modal-body"><div className="form-grid">
    <label className="field field-wide"><span>Division</span><select name="divisionId">{divisions.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>
    <label className="field"><span>Round type</span><select name="mode"><option value="round_robin">Round robin</option><option value="knockout">Knockout</option></select></label><label className="field"><span>Date</span><input name="startDate" type="date" required /></label>
    <label className="field"><span>First kick-off</span><input name="startTime" type="time" defaultValue="09:00" required /></label><label className="field"><span>Available pitches</span><input name="pitches" type="number" min="1" max="12" defaultValue="2" /></label>
    <label className="field field-wide"><span>Minutes between kick-offs</span><input name="slotMinutes" type="number" min="20" max="180" defaultValue="60" /></label>
    <div className="smart-note field-wide"><Sparkles size={18} /><div><strong>Regeneration replaces the division&apos;s current schedule.</strong><p>A live match must be completed first, protecting matchday data.</p></div></div>
  </div></div><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? <LoaderCircle className="spin" size={17} /> : <Sparkles size={17} />} Generate</button></div></form></Modal>;
}

function standingsFor(division: Division | undefined, entries: Entry[], fixtures: Fixture[]) {
  if (!division) return [];
  const rows = new Map(entries.filter(e => e.divisionId === division.id && e.status === "approved").map(entry => [entry.id, { entry, p: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0, pts: 0 }]));
  fixtures.filter(f => f.divisionId === division.id && f.status === "completed").forEach(fixture => {
    const home = rows.get(fixture.homeEntryId); const away = rows.get(fixture.awayEntryId); if (!home || !away) return;
    home.p += 1; away.p += 1; home.gf += fixture.homeScore; home.ga += fixture.awayScore; away.gf += fixture.awayScore; away.ga += fixture.homeScore;
    if (fixture.homeScore > fixture.awayScore) { home.w += 1; away.l += 1; home.pts += division.winPoints; away.pts += division.lossPoints; }
    else if (fixture.homeScore < fixture.awayScore) { away.w += 1; home.l += 1; away.pts += division.winPoints; home.pts += division.lossPoints; }
    else { home.d += 1; away.d += 1; home.pts += division.drawPoints; away.pts += division.drawPoints; }
  });
  return [...rows.values()].sort((a,b) => b.pts-a.pts || (b.gf-b.ga)-(a.gf-a.ga) || b.gf-a.gf);
}

export default function Dashboard({ user }: { user: ChatGPTUser }) {
  const [view, setView] = useState<View>("Overview"); const [data, setData] = useState<AppData>(emptyData); const [selectedId, setSelectedId] = useState("");
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [toast, setToast] = useState("");
  const [sidebar, setSidebar] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [teamOpen, setTeamOpen] = useState(false); const [fixtureOpen, setFixtureOpen] = useState(false);
  const [locationTournament,setLocationTournament]=useState<Tournament>();

  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/app", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not load data"); setData(body); setSelectedId(current => current && body.tournaments.some((t: Tournament) => t.id === current) ? current : body.tournaments[0]?.id || ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load data"); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const act = async (payload: Record<string, unknown>) => { setBusy(true); try { const response = await fetch("/api/app", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Action failed"); await load(); setCreateOpen(false); setTeamOpen(false); setFixtureOpen(false); setLocationTournament(undefined); setToast("Saved successfully"); window.setTimeout(() => setToast(""), 2800); } catch (reason) { setError(reason instanceof Error ? reason.message : "Action failed"); } finally { setBusy(false); } };
  const selected = data.tournaments.find(item => item.id === selectedId); const selectedDivisions = data.divisions.filter(item => item.tournamentId === selectedId); const divisionIds = selectedDivisions.map(item => item.id);
  const selectedEntries = data.entries.filter(item => divisionIds.includes(item.divisionId)); const selectedFixtures = data.fixtures.filter(item => divisionIds.includes(item.divisionId)); const selectedAnnouncements = data.announcements.filter(item => item.tournamentId === selectedId);
  const entryMap = useMemo(() => new Map(data.entries.map(item => [item.id, item])), [data.entries]);
  const [divisionId, setDivisionId] = useState("");
  const effectiveDivisionId = selectedDivisions.some(item => item.id === divisionId) ? divisionId : selectedDivisions[0]?.id || "";
  const activeDivision = selectedDivisions.find(item => item.id === effectiveDivisionId); const table = standingsFor(activeDivision, selectedEntries, selectedFixtures);
  const activeFixture = selectedFixtures.find(item => item.status === "live") || selectedFixtures.find(item => item.status === "scheduled") || selectedFixtures[0];
  const go = (next: View) => { setView(next); setSidebar(false); };
  const copyRegistration = async () => { if (!selected) return; await navigator.clipboard.writeText(`${window.location.origin}/register/${selected.id}`); setToast("Registration link copied"); };

  if (loading && !data.tournaments.length) return <main className="loading-screen"><Logo /><LoaderCircle className="spin" size={28} /><p>Loading your tournament workspace…</p></main>;
  return <div className="app-shell">
    <aside className={sidebar ? "sidebar open" : "sidebar"}><div className="sidebar-top"><Logo /><button className="mobile-close" onClick={() => setSidebar(false)}><X size={20} /></button></div><button className="create-sidebar" onClick={() => setCreateOpen(true)}><Plus size={18} /> Create tournament</button><nav>{nav.map(item => { const Icon=item.icon; return <button className={view===item.label?"active":""} onClick={() => go(item.label)} key={item.label}><Icon size={19} /><span>{item.label}</span>{item.label==="Inbox" && selectedAnnouncements.length>0 && <em>{selectedAnnouncements.length}</em>}</button>; })}<a className="sidebar-discover" href="/discover"><Compass size={19}/><span>Discover & register</span></a><a className="sidebar-discover" href="/account"><Users size={19}/><span>Account settings</span></a></nav><div className="sidebar-help"><span><ShieldCheck size={17} /></span><strong>Complete organizer workspace</strong><p>Every signed-in account can create and operate tournaments.</p></div><ThemeToggle/><div className="sidebar-user"><span>{user.displayName.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}</span><div><strong>{user.displayName}</strong><small>{user.email}</small></div><a href="/signout-with-chatgpt?return_to=%2Fsigned-out" aria-label="Sign out"><ArrowRight size={18} /></a></div></aside>{sidebar && <button className="sidebar-scrim" onClick={() => setSidebar(false)} />}
    <main className="main-area"><header className="topbar"><button className="menu-button" onClick={() => setSidebar(true)}><Menu size={21} /></button><div className="page-title"><h1>{view}</h1><p>{selected ? `${selected.name} · ${selected.city}` : "Create your first competition"}</p></div>{data.tournaments.length>0 && <select className="tournament-switcher" value={selectedId} onChange={e => setSelectedId(e.target.value)}>{data.tournaments.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select>}<div className="top-actions"><button className="top-icon" onClick={() => void load()} aria-label="Refresh"><RefreshCw size={18} /></button><button className="top-icon" aria-label="Notifications"><Bell size={19} /></button><button className="mobile-create" onClick={() => setCreateOpen(true)}><Plus size={20} /></button></div></header>
      <div className="content">{error && <div className="error-banner"><span>{error}</span><button onClick={() => setError("")}><X size={16} /></button></div>}
        {!data.tournaments.length ? <section className="empty-onboarding"><span><Trophy size={34} /></span><div><small className="eyebrow">Your database is ready</small><h1>Create your first real tournament</h1><p>Registrations, fixtures, results and announcements will persist here and remain after refresh.</p><button className="button primary" onClick={() => setCreateOpen(true)}><Plus size={17} /> Create tournament</button></div></section> : <>
        {view === "Overview" && <><section className="hero-strip"><div className="hero-copy"><span className="eyebrow light">Organizer control centre</span><h2>{selected?.name}</h2><p>{selected && `${dateLabel(selected.startDate)} · ${selected.venueName}, ${selected.city}`}</p><button className="button light-button" onClick={() => go("Teams")}>Manage registrations <ArrowRight size={17} /></button></div><div className="hero-visual"><div className="score-float"><small>Live database</small><strong><span>{selectedEntries.length}</span> teams</strong><p>{selectedFixtures.length} fixtures published</p></div></div></section><section className="metric-grid"><article><span className="metric-icon green"><Users size={19} /></span><div><small>Registered teams</small><strong>{selectedEntries.length}</strong><p>{selectedEntries.filter(e=>e.status==="approved").length} approved</p></div></article><article><span className="metric-icon blue"><CalendarDays size={19} /></span><div><small>Fixtures</small><strong>{selectedFixtures.length}</strong><p>{selectedFixtures.filter(f=>f.status==="completed").length} completed</p></div></article><article><span className="metric-icon orange"><IndianRupee size={19} /></span><div><small>Fees recorded</small><strong>{money(selectedEntries.filter(e=>e.paymentStatus==="paid").reduce((sum,e)=>sum+e.amountPaise,0))}</strong><p>{selectedEntries.filter(e=>e.paymentStatus==="paid").length} paid</p></div></article><article><span className="metric-icon violet"><Trophy size={19} /></span><div><small>Divisions</small><strong>{selectedDivisions.length}</strong><p>{selectedDivisions.map(d=>d.name).join(", ")}</p></div></article></section><section className="panel activity-panel"><div className="section-heading"><div><span className="eyebrow">Next steps</span><h2>Run the competition</h2></div></div><div className="attention-grid"><button onClick={() => go("Teams")}><span className="attention-icon blue"><Users size={18} /></span><div><strong>Review team entries</strong><p>{selectedEntries.filter(e=>e.status==="pending").length} awaiting approval</p></div><ArrowRight size={18} /></button><button onClick={() => setFixtureOpen(true)}><span className="attention-icon purple"><Sparkles size={18} /></span><div><strong>Generate fixtures</strong><p>Use approved teams and pitch timing</p></div><ArrowRight size={18} /></button><button onClick={() => go("Matchday")}><span className="attention-icon warning"><Swords size={18} /></span><div><strong>Open matchday</strong><p>Record live scores and events</p></div><ArrowRight size={18} /></button></div></section></>}
        {view === "Tournaments" && <><section className="page-intro"><div><span className="eyebrow">Your competitions</span><h2>Tournaments</h2><p>Exact tournament locations power fan discovery and map directions.</p></div><button className="button primary" onClick={() => setCreateOpen(true)}><Plus size={17} /> New tournament</button></section><div className="tournament-grid">{data.tournaments.map(t => { const ds=data.divisions.filter(d=>d.tournamentId===t.id); const es=data.entries.filter(e=>ds.some(d=>d.id===e.divisionId)); return <article className="tournament-card" key={t.id}><div className="card-accent" /><div className="card-topline"><span className="status status-registration"><i />{t.status.replaceAll("_"," ")}</span><button className="plain-icon" onClick={() => { if(confirm(`Delete ${t.name}? This permanently removes its teams and fixtures.`)) void act({action:"deleteTournament",tournamentId:t.id}); }}><Trash2 size={17} /></button></div><div className="trophy-orb"><Trophy size={23} /></div><h3>{t.name}</h3><p><MapPin size={14} />{t.addressLine1?`${t.venueName}, ${t.locality}, ${t.city}, ${t.state} – ${t.postalCode}`:`${t.venueName}, ${t.city} · Location incomplete`}</p>{!t.addressLine1&&<button className="location-warning" onClick={()=>setLocationTournament(t)}><MapPin size={14}/> Complete exact location to appear in Discover</button>}<div className="tag-row">{ds.map(d=><span key={d.id}>{d.name}</span>)}</div><div className="card-metrics"><div><small>Starts</small><strong>{dateLabel(t.startDate)}</strong></div><div><small>Teams</small><strong>{es.length}</strong></div></div><button className="card-link" onClick={() => {setSelectedId(t.id);go("Overview");}}>Open workspace <ArrowRight size={16} /></button></article>; })}</div></>}
        {view === "Teams" && <><section className="page-intro"><div><span className="eyebrow">Registration management</span><h2>Teams</h2><p>Approve entries, record fee status and share the public form.</p></div><div className="page-actions"><button className="button secondary" onClick={copyRegistration}><ClipboardCopy size={16} /> Copy registration link</button><button className="button primary" onClick={() => setTeamOpen(true)}><Plus size={17} /> Add team</button></div></section><section className="panel table-panel"><div className="table-toolbar"><div className="inner-search"><Search size={17} /><span>{selectedEntries.length} registrations across {selectedDivisions.length} divisions</span></div></div><div className="responsive-table"><table><thead><tr><th>Team</th><th>Division</th><th>Contact</th><th>Payment</th><th>Approval</th><th>Registered</th></tr></thead><tbody>{selectedEntries.length ? selectedEntries.map(entry => <tr key={entry.id}><td><div className="team-cell"><span>{entry.teamName.slice(0,2).toUpperCase()}</span><div><strong>{entry.teamName}</strong><small>{entry.clubName} · {entry.city}</small></div></div></td><td><span className="neutral-pill">{data.divisions.find(d=>d.id===entry.divisionId)?.name}</span></td><td><strong>{entry.contactName}</strong><br/><small>{entry.contactPhone}</small></td><td><select className="inline-select" value={entry.paymentStatus} onChange={e=>void act({action:"updateEntry",entryId:entry.id,paymentStatus:e.target.value,status:entry.status})}><option value="unpaid">Unpaid</option><option value="paid">Paid</option><option value="waived">Waived</option></select></td><td><select className="inline-select" value={entry.status} onChange={e=>void act({action:"updateEntry",entryId:entry.id,status:e.target.value,paymentStatus:entry.paymentStatus})}><option value="pending">Pending</option><option value="approved">Approved</option><option value="waitlisted">Waitlisted</option><option value="withdrawn">Withdrawn</option></select></td><td>{timeLabel(entry.registeredAt)}</td></tr>) : <tr><td colSpan={6}><div className="table-empty"><Users size={24} /><strong>No teams yet</strong><p>Add one manually or share the registration link.</p></div></td></tr>}</tbody></table></div></section></>}
        {view === "Fixtures" && <><section className="page-intro"><div><span className="eyebrow">Competition schedule</span><h2>Fixtures</h2><p>Generated from approved entries and saved immediately.</p></div><button className="button primary" onClick={() => setFixtureOpen(true)}><Sparkles size={17} /> Generate fixtures</button></section><div className="division-tabs">{selectedDivisions.map(d=><button className={effectiveDivisionId===d.id?"active":""} onClick={()=>setDivisionId(d.id)} key={d.id}>{d.name}</button>)}</div><section className="panel schedule-panel"><div className="section-heading"><div><span className="eyebrow">{activeDivision?.format.replaceAll("_"," ")}</span><h2>{activeDivision?.name} schedule</h2></div><span className="neutral-pill">{selectedFixtures.filter(f=>f.divisionId===effectiveDivisionId).length} matches</span></div><div className="timeline generated">{selectedFixtures.filter(f=>f.divisionId===effectiveDivisionId).map(f => <div className="timeline-row" key={f.id}><span className="fixture-status-dot" /><div className="time-node"><strong>{timeLabel(f.kickoffAt).split(", ").slice(-1)}</strong><small>{timeLabel(f.kickoffAt).split(", ")[0]} · Pitch {f.pitch}</small></div><div className="fixture-teams"><span><b>{entryMap.get(f.homeEntryId)?.teamName.slice(0,2).toUpperCase()}</b>{entryMap.get(f.homeEntryId)?.teamName}</span><em>{f.status==="completed"?`${f.homeScore}–${f.awayScore}`:"vs"}</em><span><b>{entryMap.get(f.awayEntryId)?.teamName.slice(0,2).toUpperCase()}</b>{entryMap.get(f.awayEntryId)?.teamName}</span></div><span className="rest-ok">{f.roundName}</span></div>)}{!selectedFixtures.some(f=>f.divisionId===effectiveDivisionId)&&<div className="table-empty"><CalendarDays size={24}/><strong>No fixtures generated</strong><p>Approve at least two teams, then generate the schedule.</p></div>}</div></section></>}
        {view === "Matchday" && <><section className="page-intro"><div><span className="eyebrow live-label"><i /> Match operations</span><h2>Matchday</h2><p>Scores and match events write directly to the tournament record.</p></div></section>{activeFixture ? <Matchday fixture={activeFixture} home={entryMap.get(activeFixture.homeEntryId)} away={entryMap.get(activeFixture.awayEntryId)} events={data.events.filter(e=>e.fixtureId===activeFixture.id)} act={act} /> : <section className="empty-onboarding compact-empty"><span><Swords size={30}/></span><div><h2>No fixture is ready</h2><p>Generate fixtures first, then return here to operate the match.</p><button className="button primary" onClick={()=>setFixtureOpen(true)}>Generate fixtures</button></div></section>}</>}
        {view === "Standings" && <><section className="page-intro"><div><span className="eyebrow">Calculated automatically</span><h2>Standings</h2><p>Only completed fixtures contribute to the table.</p></div></section><div className="division-tabs">{selectedDivisions.map(d=><button className={effectiveDivisionId===d.id?"active":""} onClick={()=>setDivisionId(d.id)} key={d.id}>{d.name}</button>)}</div><section className="panel table-panel standings-panel"><div className="responsive-table"><table><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>PTS</th></tr></thead><tbody>{table.map((row,index)=><tr className={index<2?"qualifies":""} key={row.entry.id}><td><strong>{index+1}</strong></td><td><div className="team-cell"><span>{row.entry.teamName.slice(0,2).toUpperCase()}</span><div><strong>{row.entry.teamName}</strong><small>{row.entry.clubName}</small></div></div></td><td>{row.p}</td><td>{row.w}</td><td>{row.d}</td><td>{row.l}</td><td>{row.gf}</td><td>{row.ga}</td><td>{row.gf-row.ga}</td><td><strong>{row.pts}</strong></td></tr>)}{!table.length&&<tr><td colSpan={10}><div className="table-empty"><BarChart3 size={24}/><strong>No approved teams</strong><p>Standings appear as soon as teams are approved.</p></div></td></tr>}</tbody></table></div></section></>}
        {view === "Inbox" && <Inbox tournament={selected!} announcements={selectedAnnouncements} act={act} />}
        </>}</div></main>
    {createOpen&&<CreateTournament onClose={()=>setCreateOpen(false)} onSaved={act}/>} {teamOpen&&<AddTeam divisions={selectedDivisions} onClose={()=>setTeamOpen(false)} onSaved={act}/>} {fixtureOpen&&<GenerateFixtures divisions={selectedDivisions} onClose={()=>setFixtureOpen(false)} onSaved={act}/>} {locationTournament&&<SetLocation tournament={locationTournament} onClose={()=>setLocationTournament(undefined)} onSaved={act}/>} {toast&&<div className="toast"><span className="toast-icon"><Check size={16}/></span><span>{toast}</span><button onClick={()=>setToast("")}><X size={15}/></button></div>} {busy&&<div className="busy-chip"><LoaderCircle className="spin" size={15}/> Saving</div>}
  </div>;
}

function Matchday({ fixture, home, away, events, act }: { fixture: Fixture; home?: Entry; away?: Entry; events: MatchEvent[]; act: (payload: Record<string, unknown>) => Promise<void> }) {
  const [minute,setMinute]=useState(0); const update=(h:number,a:number,status=fixture.status)=>act({action:"updateScore",fixtureId:fixture.id,homeScore:Math.max(0,h),awayScore:Math.max(0,a),status});
  const event=(entryId:string,type:string)=>act({action:"addEvent",fixtureId:fixture.id,entryId,type,matchMinute:minute});
  return <><div className="matchday-grid"><section className="live-scoreboard"><div className="scoreboard-top"><span>{fixture.roundName} · Pitch {fixture.pitch}</span><span className="live-chip"><i />{fixture.status.toUpperCase()}</span></div><div className="score-main"><div className="score-team"><span className="crest blue-crest">{home?.teamName.slice(0,2).toUpperCase()}</span><h3>{home?.teamName}</h3></div><div className="score-centre"><strong><button onClick={()=>void update(fixture.homeScore+1,fixture.awayScore,"live")}>{fixture.homeScore}</button><em>:</em><button onClick={()=>void update(fixture.homeScore,fixture.awayScore+1,"live")}>{fixture.awayScore}</button></strong><span>{minute}&apos;</span><small>{fixture.status}</small></div><div className="score-team"><span className="crest orange-crest">{away?.teamName.slice(0,2).toUpperCase()}</span><h3>{away?.teamName}</h3></div></div><div className="match-clock"><div><button onClick={()=>void update(fixture.homeScore,fixture.awayScore,"live")}>Start / resume</button><button onClick={()=>void update(fixture.homeScore,fixture.awayScore,"completed")}>Finish match</button></div><span><Clock3 size={14}/>{timeLabel(fixture.kickoffAt)}</span></div></section><section className="panel event-controls"><div className="section-heading"><div><span className="eyebrow">Match events</span><h2>Record event</h2></div></div><label className="field minute-input"><span>Match minute</span><input type="number" min="0" max="200" value={minute} onChange={e=>setMinute(Number(e.target.value))}/></label><div className="event-buttons"><button onClick={()=>home&&void event(home.id,"goal")}><span className="event-symbol goal"><CircleDot size={20}/></span><strong>{home?.teamName} goal</strong></button><button onClick={()=>away&&void event(away.id,"goal")}><span className="event-symbol goal"><CircleDot size={20}/></span><strong>{away?.teamName} goal</strong></button><button onClick={()=>home&&void event(home.id,"yellow_card")}><span className="event-symbol yellow"/><strong>Home yellow</strong></button><button onClick={()=>away&&void event(away.id,"yellow_card")}><span className="event-symbol yellow"/><strong>Away yellow</strong></button></div></section></div><section className="panel event-feed"><div className="section-heading"><div><span className="eyebrow">Persisted timeline</span><h2>Match events</h2></div></div><div className="event-list">{events.map(e=><div key={e.id}><time>{e.matchMinute}&apos;</time><span className={e.type==="yellow_card"?"feed-icon yellow-card":"feed-icon"}>{e.type==="goal"&&<CircleDot size={15}/>}</span><p><strong>{e.type.replaceAll("_"," ")}</strong><small>{e.entryId===fixture.homeEntryId?home?.teamName:away?.teamName}</small></p></div>)}{!events.length&&<div><p><strong>No events recorded yet</strong><small>Use the controls above during the match.</small></p></div>}</div></section></>;
}

function Inbox({ tournament, announcements, act }: { tournament: Tournament; announcements: Announcement[]; act: (payload: Record<string, unknown>) => Promise<void> }) {
  const [body,setBody]=useState(""); const send=async(e:FormEvent)=>{e.preventDefault(); if(!body.trim())return; await act({action:"sendAnnouncement",tournamentId:tournament.id,body});setBody("");};
  return <><section className="page-intro"><div><span className="eyebrow">Participant communication</span><h2>Announcements</h2><p>Messages remain attached to the tournament record.</p></div></section><div className="inbox-grid single-inbox"><section className="panel conversations">{announcements.map(a=><div className="conversation active" key={a.id}><span>MF</span><div><strong>All participants</strong><p>{a.body}</p></div><em>{timeLabel(a.createdAt)}</em></div>)}{!announcements.length&&<div className="table-empty"><MessageSquareText size={24}/><strong>No announcements yet</strong></div>}</section><section className="panel composer"><div className="composer-head"><div><span className="broadcast-avatar"><Users size={19}/></span><div><strong>{tournament.name} participants</strong><small>Saved announcement channel</small></div></div></div><div className="messages">{announcements.slice(0,4).reverse().map(a=><div className="sent-message" key={a.id}><p>{a.body}</p><span>{timeLabel(a.createdAt)}</span></div>)}</div><form className="message-compose" onSubmit={send}><input value={body} onChange={e=>setBody(e.target.value)} placeholder="Write an announcement…" maxLength={2000}/><button className="send-button"><Send size={18}/></button></form></section></div></>;
}
